# Generated by Django 5.2.8 on 2025-11-11 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0005_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer this order is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='crm.customer'),
        ),
    ]
