# Generated by Django 5.2.8 on 2025-11-11 18:06

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rfq_quote_quoteitem_rfqitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='expiration_date',
            field=models.DateField(default=inventory.models.get_default_expiration_date, help_text='Quote expires after this date'),
        ),
    ]
